---
title: "project"
output: 
  pdf_document:
  latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(viridis)
library(readxl)
library(faraway)
library(broom)
library(dplyr)
library(MASS)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


```{r message = FALSE}
# tidying data and adding a column with the average salary
law_data = read_csv("./data/Lawsuit.csv") %>% 
  janitor::clean_names() %>% 
  mutate(dept = recode_factor(dept, 
                              "1" = "Biochemistry/Molecular Biology", 
                              "2" = "Physiology",
                              "3" = "Genetics", 
                              "4" = "Pediatrics", 
                              "5" = "Medicine", 
                              "6" = "Surgery"),
         gender = recode_factor(gender, 
                                "1" = "Male", 
                                "0" = "Female"),
         clin = recode_factor(clin, 
                              "1" = "Primarily clinical emphasis", 
                              "0" = "Primarily research emphasis"),
         cert = recode_factor(cert, 
                              "1" = "Board certified", 
                              "0" = "Not certified"),
         rank = recode_factor(rank, 
                              "1" = "Assistant", 
                              "2" = "Associate", 
                              "3" = "Full professor"),
         avg_salary = (sal94 + sal95) / 2)
```

```{r}
# data exploration pt. 1
my_labels  =  list(dept = "Dept, n(%)", 
                   clin = "Clin, n(%)", 
                   cert = "Clin, n(%)", 
                   prate = "Prate", 
                   exper = "Exper", 
                   rank = "Rank, n(%)", 
                   sal94 = "Sal94", 
                   sal95 = "Sal95",
                   avg_salary = "Average Salary")

my_controls = tableby.control(
               total = F,
               test = F,
               numeric.stats = c("meansd", "medianq1q3"),
               digits = 2,
               digits.pct = 2)

table1 = tableby(gender ~ dept + clin + cert + prate + exper + rank + sal94 + sal95 + avg_salary, data = law_data, control = my_controls)

summary(table1, labelTranslations = my_labels, 
        title = "Demographics and co-morbidities ", text = T) %>% 
  knitr::kable()
```
